### ISSUE TITLE
#8 로그인 + 유저 정보 수정 + 로그인 확인 함수

### ISSUE THREAD

**Issue by sgwon96** [HYDongBang/DongBang_backend_new#10]
signIn
editUser
isAuthenticated

**Comment by sgwon96** [comment]
mutation{
  createUser(email:"test@naver.com" password:"1234" auth:true){
    email
    encryptedPassword
    auth
  }
}

**Comment by sgwon96** [comment]
mutation{
  signIn(email:"test@naver.com", password:"1234")
}

**Comment by sgwon96** [comment]
mutation{
  editUser(userName:"gwon", studentNumber:"2016026371", userPhoneNumber:"00", major:"information", university:"한양대"){
    userName,
    studentNumber,
    userPhoneNumber,
    major,
    university,
    encryptedPassword,
    email
  }
}

**Comment by sgwon96** [comment]
signIn 하면 나오는 토큰 복사해서 헤더에 {"Authorization" : "Bearer 토큰"} 넣고 실행하면 request에  유저 정보가 들어감

**Comment by WISUNGWON** [comment]
확인완료.

내 local에서 
schema.prisma에 작성된 user model의 email 속성이 @unique로 설정되어있지 않아서 prisma where문이 안먹는 이슈 있었음
email 속성 @unique로 바꾸고 prisma적용하니 해결됨
